07/07/2026

In [ ]:
# LIST METHODS IN PYTHON - 07-07-2026

# Original List
list1 = ["j", "d", "w", "f", "n", "22"]
print("Original List:", list1)

print("\n1. append()")
list2 = list1.copy()
list2.append("k")
print(list2)

print("\n2. extend()")
list2 = list1.copy()
list2.extend(["a", "b", "c"])
print(list2)

print("\n3. insert()")
list2 = list1.copy()
list2.insert(2, "x")
print(list2)

print("\n4. remove()")
list2 = list1.copy()
list2.remove("22")
print(list2)

print("\n5. pop()")
list2 = list1.copy()
removed = list2.pop()
print("Removed Element:", removed)
print("Updated List:", list2)

print("\n6. clear()")
list2 = list1.copy()
list2.clear()
print(list2)

print("\n7. del")
list2 = list1.copy()
print("Before del:", list2)
del list2
print("List deleted successfully.")

print("\n8. index()")
print("Index of 'w' =", list1.index("w"))

print("\n9. count()")
print("Count of '22' =", list1.count("22"))

print("\n10. sort()")
list2 = list1.copy()
list2.sort()
print(list2)

print("\n11. reverse()")
list2 = list1.copy()
list2.reverse()
print(list2)

Original List: ['j', 'd', 'w', 'f', 'n', '22']

1. append()
['j', 'd', 'w', 'f', 'n', '22', 'k']

2. extend()
['j', 'd', 'w', 'f', 'n', '22', 'a', 'b', 'c']

3. insert()
['j', 'd', 'x', 'w', 'f', 'n', '22']

4. remove()
['j', 'd', 'w', 'f', 'n']

5. pop()
Removed Element: 22
Updated List: ['j', 'd', 'w', 'f', 'n']

6. clear()
[]

7. del
Before del: ['j', 'd', 'w', 'f', 'n', '22']
List deleted successfully.

8. index()
Index of 'w' = 2

9. count()
Count of '22' = 1

10. sort()
['22', 'd', 'f', 'j', 'n', 'w']

11. reverse()
['22', 'n', 'f', 'w', 'd', 'j']


In [ ]:
#07-07-2026
keys_list = ['names', 'rollno', 'stream']
print("1", type(keys_list))

names_list = ['GJ', 'MH', 'RJ']
roll_list = [1,11,111]

dictb = dict.fromkeys(keys_list)
print("2", dictb)

dictb['names'] = names_list
dictb['rollno'] = roll_list
dictb['stream'] = ['DS', 'CS', 'EC']
dictb['city'] = [1,2,3]
dictb.update({'AQI': [101,200,300]})
print("3", dictb)

print("4", dictb.items())
print("5", dictb.keys())
print("6", dictb.values())

1 <class 'list'>
2 {'names': None, 'rollno': None, 'stream': None}
3 {'names': ['GJ', 'MH', 'RJ'], 'rollno': [1, 11, 111], 'stream': ['DS', 'CS', 'EC'], 'city': [1, 2, 3], 'AQI': [101, 200, 300]}
4 dict_items([('names', ['GJ', 'MH', 'RJ']), ('rollno', [1, 11, 111]), ('stream', ['DS', 'CS', 'EC']), ('city', [1, 2, 3]), ('AQI', [101, 200, 300])])
5 dict_keys(['names', 'rollno', 'stream', 'city', 'AQI'])
6 dict_values([['GJ', 'MH', 'RJ'], [1, 11, 111], ['DS', 'CS', 'EC'], [1, 2, 3], [101, 200, 300]])


In [ ]:
my_tuple = (1,2,3,4)
print(my_tuple)

(1, 2, 3, 4)


08/08/2026

In [ ]:
#08-07-2026
list1 = []

for i in range (10):
  list1.append(i)
  list1.append(i+3)
print(list1)
print(list1[1])

[0, 3, 1, 4, 2, 5, 3, 6, 4, 7, 5, 8, 6, 9, 7, 10, 8, 11, 9, 12]
3


In [ ]:
#08-07-2026
user_ip = " "
while user_ip.lower() != "quit" :
  user_ip = input("enter something or type QUIT to stop -")
  print("you entered", user_ip)

enter something or type QUIT to stop -6
you entered 6
enter something or type QUIT to stop -QUIT
you entered QUIT


In [ ]:
def find_cube(num):
    result = num * num * num
    return result

cube = find_cube(4)
print("Cube:", cube)

Cube: 64


In [ ]:
def calculate(num):
    for i in range(1, num + 1):
        print("Number:", i)

    count = 1
    while count <= num:
        print("Count:", count)
        count += 1

    return num * num * num
result = calculate(3)

print("Cube:", result)

Number: 1
Number: 2
Number: 3
Count: 1
Count: 2
Count: 3
Cube: 27


In [ ]:
import numpy as np
d_0 = np.array(25)
d_1 = np.array([10, 20, 30, 40, 50])
d_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

d_3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])


print(np.ndim(d_0), "\n", d_0)
print(np.ndim(d_1), "\n", d_1)
print(np.ndim(d_2), "\n", d_2)
print(np.ndim(d_3), "\n", d_3)

print(f"\nd_3[1,2,1] = {d_3[1,2,1]}")

print(f"d_3[0,1,2] = {d_3[0,1,2]}")
print(f"d_3[1,0,0] = {d_3[1,0,0]}")
print(f"Sum = {d_3[0,1,2]} + {d_3[1,0,0]} = {d_3[0,1,2] + d_3[1,0,0]}")

reshape_array = d_3.reshape(3,6)

print("\nReshaped Array:")
print(reshape_array)

print("\nTotal Elements:", d_3.size)

print("Dimensions:", d_3.ndim)

print("Shape:", d_3.shape)

flat = d_3.flatten()

print("\nFlattened Array:")
print(flat)

print("\nFlattened Array Dimension:", flat.ndim)
print("Flattened Array Shape:", flat.shape)

0 
 25
1 
 [10 20 30 40 50]
2 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

d_3[1,2,1] = 17
d_3[0,1,2] = 6
d_3[1,0,0] = 10
Sum = 6 + 10 = 16

Reshaped Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

Total Elements: 18
Dimensions: 3
Shape: (2, 3, 3)

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

Flattened Array Dimension: 1
Flattened Array Shape: (18,)


In [ ]:
from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("students.csv")

print("Original Data")
print(df)

print("\n1. Head")
print(df.head())

print("\n2. Tail")
print(df.tail())

print("\n3. Info")
print(df.info())

print("\n4. Describe")
print(df.describe())

print("\n5. Shape")
print(df.shape)

print("\n6. Columns")
print(df.columns)

print("\n7. Null Values")
print(df.isnull())

print("\n8. Total Null Values")
print(df.isnull().sum())

print("\n9. Sorted Data")
print(df.sort_values(by="Marks"))

print("\n10. Value Counts")
print(df["Gender"].value_counts())

Saving students.csv to students.csv
Original Data
   Student_ID    Name  Gender  Age Department  Marks  Attendance (%)
0         101   Aarav    Male   20        CSE     85              91
1         102    Diya  Female   19        ECE     92              96
2         103  Vivaan    Male   21         IT     78              85
3         104  Ananya  Female   20         ME     88              93
4         105   Kabir    Male   22        ECE     67              80
5         106   Meera  Female   19        CSE     95              98
6         107   Arjun    Male   21         CE     81              87
7         108    Siya  Female   20         IT     73              82
8         109  Ishaan    Male   22        ECE     89              94
9         110    Riya  Female   19         ME     76              88

1. Head
   Student_ID    Name  Gender  Age Department  Marks  Attendance (%)
0         101   Aarav    Male   20        CSE     85              91
1         102    Diya  Female   19        EC

In [ ]:
#09-07-2026

import pandas as pd

series = pd.Series([10, 20, 30, 40, 50])

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd

marks = pd.Series([85, 90, 78, 92], index=["Amit", "Priya", "Rahul", "Neha"])

print(marks)

Amit     85
Priya    90
Rahul    78
Neha     92
dtype: int64


In [11]:
import pandas as pd
import numpy as np

data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

print("Original DataFrame")
print(energy_df)

energy_df.isnull().sum()

# Remove rows with any missing values
cleaned_df = energy_df.dropna()
subset_df  = energy_df.dropna(subset = "Energy Consumption (MWh)")
print("\nData After Removing Rows with Missing Values:")
print(cleaned_df)
print(subset_df)
print(energy_df)

Original DataFrame
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Removing Rows with Missing Values:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
2    Hydropower                    2900.0               NaN
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN
  Energy Source  Energy Consumptio